### ISSUE TITLE
Create MVP wireframes

### ISSUE THREAD

**Issue by kevinnio** [magma-hackers/magmalabs-estimator#6]
### Description:
We need to build some wireframes showcasing the preliminary design of the app. Use the image in this Trello card (https://trello.com/c/05iXY7Hf/56-dise%C3%B1o-del-mvp) as an example.

### Acceptance criteria:
- We should have wireframes for at least these pages:
  - Homepage
  - Category page
  - Product page
  - Checkout page

**Comment by Hectorpkmn** [comment]
I paste below the images of the wireframes:

![Homepage.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b993f270b2d530013962057/125516c66e82c728ace21e0d46c09b97269282ae8aabf301b44fff9e2c4533317346f62972d7b77aef122f045c5a48fa41580d16aaffda2cafb02e6c981e5ab38532022d8c6853beb2901dbe0bbb25884687b1bd8b4ac6ef3820f5c6.png)

![Category page.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b993f270b2d530013962057/125516c66e82c728ace21e0d46cb958e26858cbb96a9af42a358b2d86b56357c2301a03f32dfa17dbd4029555d5f4ea8145b5a42aaf98979f4e03a238d550dffcd7f1d2598694ef1e1c84afd13b0328a488fb7b98945c2ef3c24ef828849360c48.png)

![Product page.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b993f270b2d530013962057/125516c66e82c728ace21e0d46d88695279780bdcff9be44a11fbcd6395428792c07b7692ac7b62abd102f535f5f4af9425d5912fcf9db79f0b06f77835a19f1c32f0e2a92624cf5f2d75dad0ba821834584b3bf834ec7e93f25e48f8e4b2c53.png)

![Checkout page.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b993f270b2d530013962057/125516c66e82c728ace21e0d46cb9c9f20898cbc9ba9af42a358b2d86b56357c2301a03f32dfa17dbd4029555d5f4ea8145b5a42aaf98979f4e03a238d550dffcd7f1d2598694ef1e1c84afd13b0328a478fb7b98945c2ef3c27e68f8d4d370c48.png)

**Comment by kevinnio** [comment]
Please add the Search bar to the Navbar so it appears on every page instead of just in the Category page. 

Also, add a prominent search bar to the Homepage so users landing over there can start searching immediately.

**Comment by Hectorpkmn** [comment]
I paste the corrected Wireframes below:

![Homepage.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b993f270b2d530013962057/125516c66e82c728ace21e0d46c09b97269282ae8aabf301b44fff9e2c4533317346f62972d7b77aef122f045c5a48fa41580d16aaffda2cafb02e6c981e5ab38532022d8c6853beb2901eb80bbb25884686b3b58c4fc0ec392df5c6.png)

![Category Page.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b993f270b2d530013962057/125516c66e82c728ace21e0d46cb958e26858cbb96a98f42a358b2d86b56357c2301a03f32dfa17dbd4029555d5f4ea8145b5a42aaf98979f4e03a238d550dffcd7f1d2598694ef1e1c84afd13b0328a488fb7b98945c3ed3423e38b864a3a0c48.png)

![Product Page.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b993f270b2d530013962057/125516c66e82c728ace21e0d46d88695279780bdcfd9be44a11fbcd6395428792c07b7692ac7b62abd102f535f5f4af9425d5912fcf9db79f0b06f77835a19f1c32f0e2a92624cf5f2d75dad0ba8218c4584b3bf834fc5e13b20e68d894b2c53.png)

![Checkout page.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b993f270b2d530013962057/125516c66e82c728ace21e0d46cb9c9f20898cbc9ba9af42a358b2d86b56357c2301a03f32dfa17dbd4029555d5f4ea8145b5a42aaf98979f4e03a238d550dffcd7f1d2598694ef1e1c84afd13b0328a488fb7b98945c3ed3423e18b8f4c370c48.png)
